management:
  metrics:
    export:
      influx:
        db: db0
        uri: "http://127.0.0.1:8086"
        user-name: admin
        password: passw0rd
        step: 1s
    tags:
      service: my-service1