version: '3'
services:
  influx:
    image: influxdb:1.7.7
    container_name: influx
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=passw0rd
    ports:
      - 8086:8086
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:6.3.2
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
networks:
  monitoring: